language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # Other GitHubs
  - ./download_other_githubs.sh

services:
 - xvfb

script: 
  # Build console version
  - qmake -qt=qt5 RegexTesterConsole.pro
  - make --silent
  - ./RegexTesterConsole
  # Build desktop
  - qmake -qt=qt5 RegexTesterDesktop.pro
  - make --silent
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)






